

import { createSlice } from '@reduxjs/toolkit';

// Initial state for client details
const initialState = {
  name: '',
  email: '',
  phone: '',
};

// Create a slice of the Redux store
const clientSlice = createSlice({
  name: 'client',
  initialState,
  reducers: {
    setClientDetails(state, action) {
      // Update client details in the state
      state.name = action.payload.name;
      state.email = action.payload.email;
      state.phone = action.payload.phone;
    },
    clearClientDetails(state) {
      // Clear client details
      state.name = '';
      state.email = '';
      state.phone = '';
    },
  },
});

// Export the actions generated by createSlice
export const { setClientDetails, clearClientDetails } = clientSlice.actions;

// Export the reducer to be included in the store
export default clientSlice.reducer;
